version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventario_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: outside1234
      MYSQL_DATABASE: inventario_ropa
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: inventario_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: outside1234
      DB_NAME: inventario_ropa
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    image: nginx:alpine
    container_name: inventario_frontend
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db_data: